name: VoiceChatPlaceholders
author: Tommm
version: '${project.version}'
main: com.bocktom.voicechatplaceholders.VoiceChatPlaceholders
api-version: '1.21'
folia-supported: true
depend: [ voicechat, PlaceholderAPI ]